In [1]:
import torch

In [7]:
nsamples = 3
nx, ny = 4, 4
x = torch.randn((nsamples,nx,ny))
x

tensor([[[-1.1721,  1.9136, -1.1528, -0.2948],
         [ 0.2804,  1.0514, -0.9384, -0.8857],
         [-0.0965,  1.0081, -0.8463, -0.6928],
         [ 0.0353, -1.7558,  0.6414,  0.8660]],

        [[ 1.6635,  0.5786, -1.3596,  2.3258],
         [-0.2528, -1.6170,  1.4460, -0.3554],
         [-1.7602, -0.5203,  0.1798, -1.2525],
         [-1.0245,  0.3673,  1.0796, -1.5606]],

        [[ 0.0634, -0.3220, -0.2613,  2.5417],
         [-0.5373, -0.0393, -1.2337,  0.7875],
         [ 0.0697,  0.1352,  1.0898, -1.6701],
         [ 0.7862, -0.9555, -1.1320,  0.4617]]])

In [8]:
nsamples = 3
nsteps = 5
nfeatures = 2
x = torch.randn((nsamples,nsteps,nfeatures))
x

tensor([[[-0.3209,  0.4810],
         [ 0.0688,  1.4922],
         [ 1.0459, -0.7036],
         [ 1.0614,  1.8683],
         [-0.6917, -1.1224]],

        [[-1.2658,  0.4465],
         [-1.1541, -0.2400],
         [-0.2136, -1.5266],
         [-0.2422,  0.0229],
         [-0.2706,  0.5208]],

        [[ 1.2694,  0.2155],
         [-0.9838, -1.7078],
         [ 0.2478,  0.1886],
         [-0.9808, -0.6074],
         [-0.6438,  0.7695]]])

In [6]:
x.new_zeros()

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])