In [1]:
import torch

#### Initialization

In [2]:
# from lists
x = torch.Tensor([5, 3])
x, x.shape, x.dtype, x.device

(tensor([5., 3.]), torch.Size([2]), torch.float32, device(type='cpu'))

In [3]:
# with zeros or ones
x = torch.zeros([3, 2])
x, x.shape

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 torch.Size([3, 2]))

In [4]:
y = torch.ones([2, 3])
y, y.shape

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([2, 3]))

In [5]:
# random uniform 
x = torch.rand([2, 5])
x, x.shape

(tensor([[0.1268, 0.8088, 0.6390, 0.6161, 0.2926],
         [0.9112, 0.7634, 0.5793, 0.0110, 0.8614]]),
 torch.Size([2, 5]))

In [6]:
# random normal
y = torch.randn([2, 5])
y, y.shape

(tensor([[ 0.7244,  0.7154, -0.3257, -0.0079, -0.3239],
         [ 1.1555,  1.1426,  0.0560, -0.0511, -0.0381]]),
 torch.Size([2, 5]))

#### Operations

In [7]:
x = torch.Tensor([5, 3, 1])
y = torch.Tensor([2, 4, 8])

In [8]:
# element-wise operations
print('Addition: ', x + y)
print('Subtraction: ', x - y)
print('Multiplication: ', x * y)
print('Division: ', x / y)
print((x-y).abs())

Addition:  tensor([7., 7., 9.])
Subtraction:  tensor([ 3., -1., -7.])
Multiplication:  tensor([10., 12.,  8.])
Division:  tensor([2.5000, 0.7500, 0.1250])
tensor([3., 1., 7.])


In [9]:
# math reduction
x = torch.randn([2, 5])
print(x)
print(x.sum())
print(x.abs().sum())
print(x.sum(dim=1))
print(x.max().item()) # for 0d tensors
print(x.min(dim=1))

tensor([[ 1.5452,  0.0542,  0.1319,  0.6044, -0.3302],
        [-0.1293, -1.1910, -1.3846, -1.1310,  0.3495]])
tensor(-1.4809)
tensor(6.8513)
tensor([ 2.0055, -3.4864])
1.54523766040802
torch.return_types.min(
values=tensor([-0.3302, -1.3846]),
indices=tensor([4, 2]))


In [10]:
# linear algebra operations
x = torch.tensor([ 10., 20., 30.])
m = torch.Tensor([[0,0,1],[0,2,0],[5,0,0]])
print(m.mv(x))
print(m @ x)

tensor([30., 40., 50.])
tensor([30., 40., 50.])


In [11]:
print(m @ m.T)

tensor([[ 1.,  0.,  0.],
        [ 0.,  4.,  0.],
        [ 0.,  0., 25.]])


In [12]:
torch.inverse(m @ m.T)

tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 0.2500, 0.0000],
        [0.0000, 0.0000, 0.0400]])

In [13]:
# for more linalg operations see also torch.linalg
#help(torch.linalg)

#### torch <-> numpy

In [14]:
import numpy as np

In [15]:
xnp = np.array([[1,2],[3,4]])
x = torch.Tensor(xnp)
x

tensor([[1., 2.],
        [3., 4.]])

In [16]:
x[0,1]=5
xnp[1,0]=6
x, xnp

(tensor([[1., 5.],
         [3., 4.]]),
 array([[1, 2],
        [6, 4]]))

In [17]:
xx = torch.from_numpy(xnp)
xx[0,1]=5
xnp[1,0]=7
xx, xnp

(tensor([[1, 5],
         [7, 4]]),
 array([[1, 5],
        [7, 4]]))

In [18]:
xxnp=xx.numpy()
xx[0,1]=8
xxnp[1,0]=9
xx, xxnp

(tensor([[1, 8],
         [9, 4]]),
 array([[1, 8],
        [9, 4]]))

#### Reshape

In [19]:
# Reshaping tensors
x = torch.rand([3, 4])
y = x.view([2, 6])
z = x.view(-1)
x, y, z

(tensor([[0.9938, 0.2025, 0.5539, 0.4360],
         [0.0438, 0.7893, 0.7950, 0.3225],
         [0.5695, 0.1898, 0.0792, 0.6177]]),
 tensor([[0.9938, 0.2025, 0.5539, 0.4360, 0.0438, 0.7893],
         [0.7950, 0.3225, 0.5695, 0.1898, 0.0792, 0.6177]]),
 tensor([0.9938, 0.2025, 0.5539, 0.4360, 0.0438, 0.7893, 0.7950, 0.3225, 0.5695,
         0.1898, 0.0792, 0.6177]))

In [20]:
z[0]=10
x, y, z

(tensor([[10.0000,  0.2025,  0.5539,  0.4360],
         [ 0.0438,  0.7893,  0.7950,  0.3225],
         [ 0.5695,  0.1898,  0.0792,  0.6177]]),
 tensor([[10.0000,  0.2025,  0.5539,  0.4360,  0.0438,  0.7893],
         [ 0.7950,  0.3225,  0.5695,  0.1898,  0.0792,  0.6177]]),
 tensor([10.0000,  0.2025,  0.5539,  0.4360,  0.0438,  0.7893,  0.7950,  0.3225,
          0.5695,  0.1898,  0.0792,  0.6177]))

In [21]:
xx = torch.rand([3, 4])
zz = xx.reshape(2,-1)
zz[0,1]=10
xx, zz

(tensor([[ 0.4183, 10.0000,  0.9845,  0.2047],
         [ 0.9958,  0.4986,  0.4959,  0.6163],
         [ 0.0356,  0.7438,  0.2824,  0.2793]]),
 tensor([[ 0.4183, 10.0000,  0.9845,  0.2047,  0.9958,  0.4986],
         [ 0.4959,  0.6163,  0.0356,  0.7438,  0.2824,  0.2793]]))